NUMPY

In [6]:
import numpy as np

In [7]:
mylist = [1,2,3]
type(mylist)

list

In [8]:
np.array (mylist)

array([1, 2, 3])

In [9]:
type(mylist)

list

In [10]:
arr = np.array (mylist)

In [11]:
print(arr)

[1 2 3]


In [12]:
type(arr)

numpy.ndarray

In [13]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]
##Dimension of the array can be checked by the number of square brackets
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
mymatrix = np.array(mylist)

In [15]:
mymatrix.shape

(3, 3)

In [16]:
mymatrix.ndim

2

In [17]:
mynewmatrix = np.array(mylist)


In [18]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
type(0.0)

float

In [21]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [23]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [24]:
#This operation cant be done with the help of a list
[1,1,1,1] + 10

TypeError: can only concatenate list (not "int") to list

In [25]:
np.ones(4) / 100

array([0.01, 0.01, 0.01, 0.01])

In [26]:
#Gives 100 numbers linearly spaced within the range of inclusive 0 and 100
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [27]:
len(np.linspace(0,10,11))

11

In [28]:
#Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(1)

array([0.21944765])

In [30]:
np.random.rand(5,5)

array([[0.86855363, 0.13130162, 0.92528628, 0.96464709, 0.57966393],
       [0.05498199, 0.82061569, 0.82572146, 0.64786602, 0.04864249],
       [0.6264834 , 0.30695849, 0.15138007, 0.32321679, 0.57826799],
       [0.72355801, 0.66418637, 0.35428916, 0.22608856, 0.84395114],
       [0.47104019, 0.76593047, 0.55287362, 0.94707389, 0.82946349]])

In [31]:
np.random.randn(1)

array([0.99333659])

In [32]:
np.random.randn(10)

array([-1.04294003,  0.32167372,  0.33784026, -0.29542968,  0.85621698,
       -0.86659818, -1.00655476,  0.73326669, -0.12075686, -1.83283385])

In [33]:
np.random.randint(1,100,10)

array([46, 64, 59, 17, 37, 56, 15, 76, 22, 54])

In [34]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [35]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [36]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
ranarr = np.random.randint(0,50,10)

In [39]:
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [40]:
arr.shape

(25,)

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
 ranarr.max(
 )

48

In [43]:
ranarr.min ()

10

In [44]:
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [45]:
ranarr.argmax()

1

In [46]:
ranarr.argmin ()

6

In [47]:
ranarr.dtype

dtype('int64')

INDEXING AND SELECTION

In [48]:
arr = np.arange(0,11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr [9]

9

In [51]:
arr [1:5]

array([1, 2, 3, 4])

In [52]:
arr [0:5]

array([0, 1, 2, 3, 4])

In [53]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [55]:
new_arr = arr / 2

In [56]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [59]:
slice_of_arr = arr[0:6]

In [60]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [61]:
slice_of_arr[:] = 99

In [62]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [63]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr_copy = arr.copy()

In [65]:
arr_copy[:] = 1000

In [66]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
#indexing on 2d array
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [69]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
 arr_2d. shape

(3, 3)

In [71]:
arr_2d [1]

array([20, 25, 30])

In [72]:
arr_2d [1] [1]

25

In [73]:
arr_2d[1,1]

25

In [74]:
arr_2d [2,2]

45

In [75]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [76]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [77]:
arr = np.arange(1,11)

In [78]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [80]:
arr [arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
bool_arr = arr > 4

In [82]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [83]:
arr [bool_arr] 

array([ 5,  6,  7,  8,  9, 10])

In [84]:
arr [arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [85]:
arr [arr <= 6]

array([1, 2, 3, 4, 5, 6])

NUMPY OPERATIONS

In [86]:
arr = np.arange(0,10)

In [87]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [89]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [90]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [91]:
(arr + 2) / 100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [92]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [94]:
1/arr

/var/folders/d2/4nwt8r4x76q0rpvrksyzkj880000gn/T/ipykernel_4011/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [95]:
arr/arr

/var/folders/d2/4nwt8r4x76q0rpvrksyzkj880000gn/T/ipykernel_4011/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [96]:
np.sqrt (arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [97]:
np.log(arr)

/var/folders/d2/4nwt8r4x76q0rpvrksyzkj880000gn/T/ipykernel_4011/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [98]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [99]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [100]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [101]:
arr.sum()

45

In [102]:
arr.mean()

4.5

In [103]:
arr.max()

9

In [104]:
arr.min()

0

In [105]:
arr_2d = np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [106]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
arr_2d.shape

(3, 4)

In [108]:
arr_2d.sum(
)

78

In [109]:
#Give me the sum across the Rows
arr_2d.sum(axis = 0)
#Sum of the all the values in the columns

array([15, 18, 21, 24])

In [110]:
#Sum of all the values of the Rows
arr_2d.sum (axis = 1)


array([10, 26, 42])